#ifndef __DEFINE_H__
#define __DEFINE_H__

#include <Arduino.h>

enum HWPin {
    IR1_THERMISTOR = GPIO_NUM_0,
    IR1_THERMOPILE = GPIO_NUM_4,
    IR2_THERMISTOR = GPIO_NUM_2,
    IR2_THERMOPILE = GPIO_NUM_15,
    IR3_THERMISTOR = GPIO_NUM_12,
    IR3_THERMOPILE = GPIO_NUM_13,
    IR4_THERMISTOR = GPIO_NUM_14,
    IR4_THERMOPILE = GPIO_NUM_27,
    IR5_THERMISTOR = GPIO_NUM_26,
    IR5_THERMOPILE = GPIO_NUM_25,
    IR6_THERMISTOR = GPIO_NUM_33,
    IR6_THERMOPILE = GPIO_NUM_32,
    IR7_THERMISTOR = GPIO_NUM_35,
    IR7_THERMOPILE = GPIO_NUM_34,
    IR8_THERMISTOR = GPIO_NUM_39,
    IR8_THERMOPILE = GPIO_NUM_36,
};

#define THERMOPILE_GAIN 246
#define THERMOPILE_OFFSET 0.55

#endif  // __DEFINE_H__